# python main.py --config configs/cifar10.yaml --num_attributes=3 --eps=1 --t=7 --lam=0.01 --seed=4 &
dataset: cifar10
attributes: cifar10
model_type: clip
model_size: ViT-B/32
linear_epochs: 1000
reinit: true # True/False
lr: 0.01
batch_size: 4096
epochs: 2000
linear_model: [linear, linear] 
score_model: [linear]

