# python main.py --config configs/cub.yaml --num_attributes=3 --eps=1 --t=10 --lam=1 --seed=0 &
dataset: cub
attributes: cub
model_type: clip
model_size: ViT-B/32
linear_epochs: 5000
reinit: false
lr: 0.01
batch_size: 32
epochs: 8000
linear_model: [linear, linear] 
score_model: [linear]
