# python main.py --config configs/food_bn.yaml --num_attributes=3 --eps=1 --t=1 --lam=1 --seed=0 &
dataset: food
attributes: food
model_type: clip
model_size: ViT-B/32
linear_epochs: 200
reinit: true
lr: 0.01
batch_size: 4096
epochs: 4000
linear_model: [linear, bn, linear] 
score_model: [bn, linear]
